[build]
builder = "RAILPACK"

[deploy]
startCommand = "uvicorn api_server:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"

[[deploy.volumes]]
mountPath = "/app/data"
name = "cs2_database_volume"

[runtime]
variables = { }