[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"

[[deploy.volumes]]
mountPath = "/app/data"
name = "cs2_database_volume"

[runtime]
variables = { }